apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-one
spec:
  replicas: 2
  selector:
    matchLabels:
      system: ReplicaOne
  template:
    metadata:
      name: rs-one
      labels:
        system: ReplicaOne
    spec:
      containers:
        - name: nginx
          image: nginx:1.9.1
          ports:
          - containerPort: 80